/**
 * Redux Form Actions
 */
export const ADD_RECIPE = "ADD_RECIPE";
export const RECIPE_ACCESS_FAILED = "RECIPE_ACCESS_FAILED";
export const RECIPES_LOADING = "RECIPES_LOADING";

export const ADD_RECIPE_TYPE = "ADD_RECIPE_TYPE";
export const RECIPE_TYPE_ACCESS_FAILED = "RECIPE_TYPE_ACCESS_FAILED";
export const RECIPE_TYPES_LOADING = "RECIPES_TYPES_LOADING";

export const ADD_TO_BLOG = "ADD_TO_BLOG";
export const BLOG_ACCESS_FAILED = "BLOG_ACCESS_FAILED";
export const BLOG_LOADING = "BLOG_LOADING";

export const ADD_FEEDBACK = "ADD_FEEDBACK";
export const FEEDBACK_ACCESS_FAILED = "FEEDBACK_ACCESS_FAILED";
export const FEEDBACK_LOADING = "FEEDBACK_LOADING";
